///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Mygit_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Mygit_projRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("4b199fea-c876-43cd-9253-05de3e283635")]
    public partial class Mygit_projRepository : RepoGenBaseFolder
    {
        static Mygit_projRepository instance = new Mygit_projRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Mygit_projRepository element repository.
        /// </summary>
        [RepositoryFolder("4b199fea-c876-43cd-9253-05de3e283635")]
        public static Mygit_projRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Mygit_projRepository() 
            : base("Mygit_projRepository", "/", null, 0, false, "4b199fea-c876-43cd-9253-05de3e283635", ".\\RepositoryImages\\Mygit_projRepository4b199fea.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4b199fea-c876-43cd-9253-05de3e283635")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class Mygit_projRepositoryFolders
    {
    }
#pragma warning restore 0436
}